export const ITEMS = {
	adults_wallet: {
		name: 'Adult\'s Wallet',
		ref: 'adults_wallet',
		critical: false,
		dungeon: false,
		progression: {
			0: 'adults_wallet',
			1: 'giants_wallet',
		},
	},
	big_poe: {
		name: 'Big Poe',
		ref: 'big_poe',
		critical: false,
		dungeon: false,
		progression: false,
	},
	biggorons_sword: {
		name: 'Biggoron\'s Sword',
		ref: 'biggorons_sword',
		critical: false,
		dungeon: false,
		progression: {
			0: 'kokiri_sword',
			1: 'master_sword',
			2: 'biggorons_sword',
		},
	},
	blue_fire: {
		name: 'Blue Fire',
		ref: 'blue_fire',
		critical: false,
		dungeon: false,
		progression: false,
	},
	blue_potion: {
		name: 'Blue Potion',
		ref: 'blue_potion',
		critical: false,
		dungeon: false,
		progression: false,
	},
	bomb: {
		name: 'Bombs',
		ref: 'bomb',
		critical: false,
		dungeon: false,
		progression: false,
	},
	bomb_bag_20: {
		name: 'Bomb Bag (20)',
		ref: 'bomb_bag_20',
		critical: true,
		dungeon: false,
		progression: {
			0: 'bomb_bag_20',
			1: 'bomb_bag_30',
			2: 'bomb_bag_40',
		},
	},
	bomb_bag_30: {
		name: 'Bomb Bag (30)',
		ref: 'bomb_bag_30',
		critical: false,
		dungeon: false,
		progression: {
			0: 'bomb_bag_20',
			1: 'bomb_bag_30',
			2: 'bomb_bag_40',
		},
	},
	bomb_bag_40: {
		name: 'Bomb Bag (40)',
		ref: 'bomb_bag_40',
		critical: false,
		dungeon: false,
		progression: {
			0: 'bomb_bag_20',
			1: 'bomb_bag_30',
			2: 'bomb_bag_40',
		},
	},
	bombchu: {
		name: 'Bombchu',
		ref: 'bombchu',
		critical: false,
		dungeon: false,
		progression: false,
	},
	boomerang: {
		name: 'Boomerang',
		ref: 'boomerang',
		critical: true,
		dungeon: false,
		progression: false,
	},
	boss_key: {
		name: 'Boss Key',
		ref: 'boss_key',
		critical: false,
		dungeon: true,
		progression: false,
	},
	bottle: {
		name: 'Bottle',
		ref: 'bottle',
		critical: false,
		dungeon: false,
		progression: {
			0: 'bottle',
			1: 'bottle',
			2: 'bottle',
			3: 'bottle',
		},
	},
	broken_goron_sword: {
		name: 'Broken Goron Sword',
		ref: 'broken_goron_sword',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	bullet_bag_30: {
		name: 'Bullet Bag (30)',
		ref: 'bullet_bag_30',
		critical: false,
		dungeon: false,
		progression: {
			0: 'bullet_bag_30',
			1: 'bullet_bag_40',
			2: 'bullet_bag_50',
		},
	},
	bullet_bag_40: {
		name: 'Bullet Bag (40)',
		ref: 'bullet_bag_40',
		critical: false,
		dungeon: false,
		progression: {
			0: 'bullet_bag_30',
			1: 'bullet_bag_40',
			2: 'bullet_bag_50',
		},
	},
	bullet_bag_50: {
		name: 'Bullet Bag (50)',
		ref: 'bullet_bag_50',
		critical: false,
		dungeon: false,
		progression: {
			0: 'bullet_bag_30',
			1: 'bullet_bag_40',
			2: 'bullet_bag_50',
		},
	},
	bunny_hood: {
		name: 'Bunny Hood',
		ref: 'bunny_hood',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	claim_check: {
		name: 'Claim Check',
		ref: 'claim_check',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	cojiro: {
		name: 'Cojiro',
		ref: 'cojiro',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	compass: {
		name: 'Compass',
		ref: 'compass',
		critical: false,
		dungeon: true,
		progression: false,
	},
	cucco: {
		name: 'Cucco',
		ref: 'cucco',
		critical: false,
		dungeon: false,
		progression: {
			0: 'weird_egg',
			1: 'cucco',
		},
	},
	deku_nut: {
		name: 'Deku Nut',
		ref: 'deku_nut',
		critical: false,
		dungeon: false,
		progression: false,
	},
	deku_seeds: {
		name: 'Deku Seeds',
		ref: 'deku_seeds',
		critical: false,
		dungeon: false,
		progression: false,
	},
	deku_shield: {
		name: 'Deku Shield',
		ref: 'deku_shield',
		critical: true,
		dungeon: false,
		progression: {
			0: 'deku_shield',
			1: 'hylian_shield',
			2: 'mirror_shield',
		},
	},
	deku_stick: {
		name: 'Deku Stick',
		ref: 'deku_stick',
		critical: true,
		dungeon: false,
		progression: false,
	},
	dins_fire: {
		name: 'Din\'s Fire',
		ref: 'dins_fire',
		critical: true,
		dungeon: false,
		progression: false,
	},
	dungeon_map: {
		name: 'Dungeon Map',
		ref: 'dungeon_map',
		critical: false,
		dungeon: true,
		progression: false,
	},
	empty_bottle: {
		name: 'Empty Bottle',
		ref: 'empty_bottle',
		critical: false,
		dungeon: false,
		progression: false,
	},
	eyeball_frog: {
		name: 'Eyeball Frog',
		ref: 'eyeball_frog',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	eyedrops: {
		name: 'Eyedrops',
		ref: 'eyedrops',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	fairy_bow: {
		name: 'Fairy Bow',
		ref: 'fairy_bow',
		critical: true,
		dungeon: false,
		progression: false,
	},
	fairy_ocarina: {
		name: 'Fairy Ocarina',
		ref: 'fairy_ocarina',
		critical: true,
		dungeon: false,
		progression: {
			0: 'fairy_ocarina',
			1: 'ocarina_of_time',
		},
	},
	fairy_slingshot: {
		name: 'Fairy Slingshot',
		ref: 'fairy_slingshot',
		critical: true,
		dungeon: false,
		progression: false,
	},
	farores_wind: {
		name: 'Farore\'s Wind',
		ref: 'farores_wind',
		critical: false,
		dungeon: false,
		progression: false,
	},
	fire_arrow: {
		name: 'Fire Arrows',
		ref: 'fire_arrow',
		critical: false,
		dungeon: false,
		progression: false,
	},
	fish: {
		name: 'Fish',
		ref: 'fish',
		critical: false,
		dungeon: false,
		progression: false,
	},
	gerudo_card: {
		name: 'Gerudo Card',
		ref: 'gerudo_card',
		critical: false,
		dungeon: false,
		progression: false,
	},
	gerudo_mask: {
		name: 'Gerudo Mask',
		ref: 'gerudo_mask',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	giants_wallet: {
		name: 'Giant\'s Wallet',
		ref: 'giants_wallet',
		critical: false,
		dungeon: false,
		progression: {
			0: '',
			1: 'adults_wallet',
			2: 'giants_wallet',
		},
	},
	gold_scale: {
		name: 'Gold Scale',
		ref: 'gold_scale',
		critical: false,
		dungeon: false,
		progression: {
			0: 'silver_scale',
			1: 'gold_scale',
		},
	},
	golden_gauntlets: {
		name: 'Golden Gauntlets',
		ref: 'golden_gauntlets',
		critical: true,
		dungeon: false,
		progression: {
			0: 'goron_bracelet',
			1: 'silver_gauntlets',
			2: 'golden_gauntlets',
		},
	},
	goron_bracelet: {
		name: 'Goron Bracelet',
		ref: 'goron_bracelet',
		critical: true,
		dungeon: false,
		progression: {
			0: 'goron_bracelet',
			1: 'silver_gauntlets',
			2: 'golden_gauntlets',
		},
	},
	goron_mask: {
		name: 'Goron Mask',
		ref: 'goron_mask',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	goron_tunic: {
		name: 'Goron Tunic',
		ref: 'goron_tunic',
		critical: true,
		dungeon: false,
		progression: false,
	},
	green_potion: {
		name: 'Green Potion',
		ref: 'green_potion',
		critical: false,
		dungeon: false,
		progression: false,
	},
	heart_container: {
		name: 'Heart Container',
		ref: 'heart_container',
		critical: false,
		dungeon: false,
		progression: false,
	},
	heart_piece: {
		name: 'Heart Piece',
		ref: 'heart_piece',
		critical: false,
		dungeon: false,
		progression: false,
	},
	hookshot: {
		name: 'Hookshot',
		ref: 'hookshot',
		critical: true,
		dungeon: false,
		progression: {
			0: 'hookshot',
			1: 'longshot',
		},
	},
	magic_beans: {
		name: 'Magic Beans',
		ref: 'magic_beans',
		critical: false,
		dungeon: false,
		progression: false,
	},
	hover_boots: {
		name: 'Hover Boots',
		ref: 'hover_boots',
		critical: true,
		dungeon: false,
		progression: false,
	},
	hylian_shield: {
		name: 'Hylian Shield',
		ref: 'hylian_shield',
		critical: true,
		dungeon: false,
		progression: {
			0: 'deku_shield',
			1: 'hylian_shield',
			2: 'mirror_shield',
		},
	},
	ice_arrow: {
		name: 'Ice Arrow',
		ref: 'ice_arrow',
		critical: false,
		dungeon: false,
		progression: false,
	},
	iron_boots: {
		name: 'Iron Boots',
		ref: 'iron_boots',
		critical: true,
		dungeon: false,
		progression: false,
	},
	keaton_mask: {
		name: 'Keaton Mask',
		ref: 'keaton_mask',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	kokiri_sword: {
		name: 'Kokiri Sword',
		ref: 'kokiri_sword',
		critical: true,
		dungeon: false,
		progression: {
			0: 'kokiri_sword',
			1: 'master_sword',
			2: 'biggorons_sword',
		},
	},
	large_magic_jar: {
		name: 'Full Magic',
		ref: 'large_magic_jar',
		critical: false,
		dungeon: false,
		progression: {
			0: 'small_magic_jar',
			1: 'large_magic_jar',
		},
	},
	lens_of_truth: {
		name: 'Lens of Truth',
		ref: 'lens_of_truth',
		critical: true,
		dungeon: false,
		progression: false,
	},
	light_arrow: {
		name: 'Light Arrow',
		ref: 'light_arrow',
		critical: true,
		dungeon: false,
		progression: false,
	},
	longshot: {
		name: 'Longshot',
		ref: 'longshot',
		critical: true,
		dungeon: false,
		progression: {
			0: 'hookshot',
			1: 'longshot',
		},
	},
	mask_of_truth: {
		name: 'Mask of Truth',
		ref: 'mask_of_truth',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	master_sword: {
		name: 'Master Sword',
		ref: 'master_sword',
		critical: true,
		dungeon: false,
		progression: {
			0: 'kokiri_sword',
			1: 'master_sword',
			2: 'biggorons_sword',
		},
	},
	megaton_hammer: {
		name: 'Megaton Hammer',
		ref: 'megaton_hammer',
		critical: true,
		dungeon: false,
		progression: false,
	},
	milk: {
		name: 'Lon Lon Milk',
		ref: 'milk',
		critical: false,
		dungeon: false,
		progression: false,
	},
	mirror_shield: {
		name: 'Mirror Shield',
		ref: 'mirror_shield',
		critical: true,
		dungeon: false,
		progression: {
			0: 'deku_shield',
			1: 'hylian_shield',
			2: 'mirror_shield',
		},
	},
	nayrus_love: {
		name: 'Nayru\'s Love',
		ref: 'nayrus_love',
		critical: false,
		dungeon: false,
		progression: false,
	},
	ocarina_of_time: {
		name: 'Ocarina of Time',
		ref: 'ocarina_of_time',
		critical: false,
		dungeon: false,
		progression: {
			0: 'fairy_ocarina',
			1: 'ocarina_of_time',
		},
	},
	odd_mushroom: {
		name: 'Odd Mushroom',
		ref: 'odd_mushroom',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	odd_potion: {
		name: 'Odd Potion',
		ref: 'odd_potion',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	perscription: {
		name: 'Perscription',
		ref: 'perscription',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	poachers_saw: {
		name: 'Poacher\'s Saw',
		ref: 'poachers_saw',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	pocket_cucco: {
		name: 'Pocket Cucco',
		ref: 'pocket_cucco',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	pocket_egg: {
		name: 'Pocket Egg',
		ref: 'weird_egg',
		critical: false,
		dungeon: false,
		progression: {
			0: 'pocket_egg',
			1: 'pocket_cucco',
			2: 'cojiro',
			3: 'odd_mushroom',
			4: 'odd_potion',
			5: 'poachers_saw',
			6: 'broken_goron_sword',
			7: 'perscription',
			8: 'eyeball_frog',
			9: 'eyedrops',
			10: 'claim_check',
		},
	},
	quiver_30: {
		name: 'Quiver (30)',
		ref: 'quiver_30',
		critical: false,
		dungeon: false,
		progression: {
			0: 'quiver_30',
			1: 'quiver_40',
			2: 'quiver_50',
		},
	},
	quiver_40: {
		name: 'Quiver (40)',
		ref: 'quiver_40',
		critical: false,
		dungeon: false,
		progression: {
			0: 'quiver_30',
			1: 'quiver_40',
			2: 'quiver_50',
		},
	},
	quiver_50: {
		name: 'Quiver (50)',
		ref: 'quiver_50',
		critical: false,
		dungeon: false,
		progression: {
			0: 'quiver_30',
			1: 'quiver_40',
			2: 'quiver_50',
		},
	},
	rupee: {
		name: 'Rupees, etc',
		ref: 'rupee',
		critical: false,
		dungeon: false,
		progression: false,
	},
	rutos_letter: {
		name: 'Ruto\'s Letter',
		ref: 'rutos_letter',
		critical: true,
		dungeon: false,
		progression: false,
	},
	silver_gauntlets: {
		name: 'Silver Gauntlets',
		ref: 'silver_gauntlets',
		critical: true,
		dungeon: false,
		progression: {
			0: 'goron_bracelet',
			1: 'silver_gauntlets',
			2: 'golden_gauntlets',
		},
	},
	silver_scale: {
		name: 'Silver Scale',
		ref: 'silver_scale',
		critical: true,
		dungeon: false,
		progression: {
			0: 'silver_scale',
			1: 'gold_scale',
		},
	},
	skull_mask: {
		name: 'Skull Mask',
		ref: 'skull_mask',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	small_key: {
		name: 'Small Key',
		ref: 'small_key',
		critical: false,
		dungeon: true,
		progression: false,
	},
	small_magic_jar: {
		name: '1/2 Magic',
		ref: 'small_magic_jar',
		critical: false,
		dungeon: false,
		progression: {
			0: 'small_magic_jar',
			1: 'large_magic_jar',
		},
	},
	spooky_mask: {
		name: 'Spooky Mask',
		ref: 'spooky_mask',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	weird_egg: {
		name: 'Weird Egg',
		ref: 'weird_egg',
		critical: true,
		dungeon: false,
		progression: {
			0: 'weird_egg',
			1: 'cucco',
		},
	},
	zeldas_letter: {
		name: 'Zelda\'s Letter',
		ref: 'zeldas_letter',
		critical: true,
		dungeon: false,
		progression: false,
	},
	zora_mask: {
		name: 'Zora Mask',
		ref: 'zora_mask',
		critical: false,
		dungeon: false,
		progression: {
			0: 'keaton_mask',
			1: 'skull_mask',
			2: 'spooky_mask',
			3: 'bunny_hood',
			4: 'zora_mask',
			5: 'goron_mask',
			6: 'gerudo_mask',
			7: 'mask_of_truth',
		},
	},
	zora_tunic: {
		name: 'Zora Tunic',
		ref: 'zora_tunic',
		critical: true,
		dungeon: false,
		progression: false,
	},
}

export const SEALS = {
	fire_medallion: {
		name: 'Fire Medallion',
		ref: 'fire_medallion',
	},
	forest_medallion: {
		name: 'Forest Medallion',
		ref: 'forest_medallion',
	},
	gorons_ruby: {
		name: 'Goron\'s Ruby',
		ref: 'gorons_ruby',
	},
	kokiri_emerald: {
		name: 'Kokiri Emerald',
		ref: 'kokiri_emerald',
	},
	light_medallion: {
		name: 'Light Medallion',
		ref: 'light_medallion',
	},
	shadow_medallion: {
		name: 'Shadow Medallion',
		ref: 'shadow_medallion',
	},
	spirit_medallion: {
		name: 'Spirit Medallion',
		ref: 'spirit_medallion',
	},
	water_medallion: {
		name: 'Water Medallion',
		ref: 'water_medallion',
	},
	zoras_sapphire: {
		name: 'Zora\'s Sapphire',
		ref: 'zoras_sapphire',
	},
}

export const SONGS = {
	bolero_of_fire: {
		name: 'Bolero of Fire',
		ref: 'bolero_of_fire',
		warp: true,
		critical: false,
	},
	eponas_song: {
		name: 'Epona\'s Song',
		ref: 'eponas_song',
		warp: false,
		critical: false,
	},
	grey_note: {
		name: '',
		ref: 'grey_note',
		warp: true,
		critical: false,
	},
	minuet_of_forest: {
		name: 'Minuet of the Forest',
		ref: 'minuet_of_forest',
		warp: true,
		critical: false,
	},
	nocturne_of_shadows: {
		name: 'Nocturne of Shadows',
		ref: 'nocturne_of_shadows',
		warp: true,
		critical: false,
	},
	prelude_of_light: {
		name: 'Prelude of Light',
		ref: 'prelude_of_light',
		warp: true,
		critical: false,
	},
	requiem_of_spirit: {
		name: 'Requium of Spirit',
		ref: 'requiem_of_spirit',
		warp: true,
		critical: false,
	},
	sarias_song: {
		name: 'Saria\'s Song',
		ref: 'sarias_song',
		warp: false,
		critical: true,
	},
	serenade_of_water: {
		name: 'Serenade of Water',
		ref: 'serenade_of_water',
		warp: true,
		critical: false,
	},
	song_of_storms: {
		name: 'Song of Storms',
		ref: 'song_of_storms',
		warp: false,
		critical: false,
	},
	song_of_time: {
		name: 'Song of Time',
		ref: 'song_of_time',
		warp: false,
		critical: true,
	},
	suns_song: {
		name: 'Sun\'s Song',
		ref: 'suns_song',
		warp: false,
		critical: false,
	},
	zeldas_lullaby: {
		name: 'Zelda\'s Lullaby',
		ref: 'zeldas_lullaby',
		warp: false,
		critical: true,
	},
}

// Collections
export const TRADE_SEQUENCE = [
	ITEMS.pocket_egg,
	ITEMS.pocket_cucco,
	ITEMS.cojiro,
	ITEMS.odd_mushroom,
	ITEMS.odd_potion,
	ITEMS.poachers_saw,
	ITEMS.broken_goron_sword,
	ITEMS.perscription,
	ITEMS.eyeball_frog,
	ITEMS.eyedrops,
	ITEMS.claim_check,
]

export const MASK_SEQUENCE = [
	ITEMS.keaton_mask,
	ITEMS.skull_mask,
	ITEMS.spooky_mask,
	ITEMS.bunny_hood,
	ITEMS.zora_mask,
	ITEMS.goron_mask,
	ITEMS.mask_of_truth,
]

export const EQUIPMENT = [
	ITEMS.kokiri_sword,
	ITEMS.master_sword,
	ITEMS.biggorons_sword,
	ITEMS.deku_shield,
	ITEMS.hylian_shield,
	ITEMS.mirror_shield,
	ITEMS.goron_tunic,
	ITEMS.zora_tunic,
	ITEMS.iron_boots,
	ITEMS.hover_boots,
]

export const UPGRADES = [
	ITEMS.goron_bracelet,
	ITEMS.silver_gauntlets,
	ITEMS.golden_gauntlets,
	ITEMS.silver_scale,
	ITEMS.gold_scale,
	ITEMS.bullet_bag_30,
	ITEMS.bullet_bag_40,
	ITEMS.bullet_bag_50,
	ITEMS.bomb_bag_20,
	ITEMS.bomb_bag_30,
	ITEMS.bomb_bag_40,
	ITEMS.quiver_30,
	ITEMS.quiver_40,
	ITEMS.quiver_50,
	ITEMS.adults_wallet,
	ITEMS.giants_wallet,
]

export const ORDERED_ITEMS = [
	ITEMS.deku_stick,
	ITEMS.fairy_slingshot,
	ITEMS.boomerang,
	ITEMS.lens_of_truth,
	ITEMS.fairy_ocarina,
	ITEMS.ocarina_of_time,
	ITEMS.deku_nut,
	ITEMS.bomb,
	ITEMS.bombchu,
	ITEMS.magic_beans,
	ITEMS.megaton_hammer,
	ITEMS.hookshot,
	ITEMS.longshot,
	ITEMS.fairy_bow,
	ITEMS.fire_arrow,
	ITEMS.ice_arrow,
	ITEMS.light_arrow,
	ITEMS.nayrus_love,
	ITEMS.farores_wind,
	ITEMS.dins_fire,
	ITEMS.bottle,
	ITEMS.bottle,
	ITEMS.bottle,
	ITEMS.bottle,
	ITEMS.zeldas_letter,
	ITEMS.rutos_letter,
	...TRADE_SEQUENCE,
	...MASK_SEQUENCE,
	...EQUIPMENT,
	...UPGRADES,
]

export const ALL_ITEMS = {
	...ITEMS,
	...SONGS,
	...SEALS,
}
